version: 2.1

# this designates this configuration file as a setup workflow configuration
setup: true 

# the continuation orb is required in order to use a setup workflow
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
            python generate-config.py > generated_config.yml 
      - persist-to-workspace:
          root: /tmp/dir
          paths:
            - generated_config.yml

workflows:
  setup:
    jobs:
      - setup
      - continuation/continue:
          requires:
            - setup
          pre-steps: 
            - attach-workspace:
                at: /tmp/dir
          configuration_path: /tmp/dir/generated_config.yml

