version: 2.1

# this designates this configuration file as a setup workflow configuration
setup: true 

# the continuation orb is required in order to use a setup workflow
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout # checkout code
      - run:
          name: Set up pyyaml
          command: |
            pip install pyyaml
      - run: # run a command
          name: Generate config
          command: |
            python generate-config.py > generated_config.yml 
      - persist_to_workspace:
          root: .
          paths:
            - generated_config.yml
      - run:
          command: |
            echo $CIRCLE_CONTINUATION_KEY > continuation_key
      - store_artifacts:
          path: generated_config.yml
      - store_artifacts:
          path: continuation_key

workflows:
  setup:
    jobs:
      - setup

