version: 2.1

# this designates this configuration file as a setup workflow configuration
setup: true 

# the continuation orb is required in order to use a setup workflow
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
            python generate-config.py > generated_config.yml 
      - continuation/continue:
          configuration_path: generated_config.yml # use newly generated config to continue

workflows:
  setup:
    jobs:
      - setup
